package luolong.mybaties.generator.mapper;

import java.util.List;
import luolong.mybaties.generator.pojo.Orders;
import luolong.mybaties.generator.pojo.OrdersExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface OrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_2018_1
     *
     * @mbg.generated Tue Jun 26 15:17:14 CST 2018
     */
    long countByExample(OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_2018_1
     *
     * @mbg.generated Tue Jun 26 15:17:14 CST 2018
     */
    int deleteByExample(OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_2018_1
     *
     * @mbg.generated Tue Jun 26 15:17:14 CST 2018
     */
    int insert(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_2018_1
     *
     * @mbg.generated Tue Jun 26 15:17:14 CST 2018
     */
    int insertSelective(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_2018_1
     *
     * @mbg.generated Tue Jun 26 15:17:14 CST 2018
     */
    List<Orders> selectByExampleWithBLOBs(OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_2018_1
     *
     * @mbg.generated Tue Jun 26 15:17:14 CST 2018
     */
    List<Orders> selectByExample(OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_2018_1
     *
     * @mbg.generated Tue Jun 26 15:17:14 CST 2018
     */
    int updateByExampleSelective(@Param("record") Orders record, @Param("example") OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_2018_1
     *
     * @mbg.generated Tue Jun 26 15:17:14 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Orders record, @Param("example") OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_2018_1
     *
     * @mbg.generated Tue Jun 26 15:17:14 CST 2018
     */
    int updateByExample(@Param("record") Orders record, @Param("example") OrdersExample example);

    Orders selectById(@Param("id") String id);
}